-- ============================================================================
-- EPIC-031 — seed programs (GENERATED FILE — do not hand-edit)
-- Generated by scripts/sync-seed-programs.mjs from seeds/*.json
-- Generated: 2026-07-24T21:33:47.630Z · seeds: brick-by-brick.json, redline-recomp.json
-- Doctrine D16 gate: PASSED at generation time.
-- PREREQUISITES (in order): epic031_program_library.sql, epic031_exercises_seed.sql.
-- DO NOT apply to live Supabase before Kerwin's SQL review.
-- ============================================================================

-- Principles first: the D16 trigger on workout_templates requires every
-- science_overrides key to already have a program_principles row.
insert into public.program_principles (principle_key, claim, rationale, source_citation, created_by)
values ('rep_floor', 'A final-phase 3-5 rep strength block is legal inside a build_muscle (hypertrophy) program, deviating from the D10 band floor of 6.', 'Phase potentiation: after eight weeks of 12-15 and 9-11 hypertrophy work, a short heavy block converts accumulated volume into expressible strength and feeds the week-12 realization test. Scoped to primary lifts in phase 3 only; accessories stay at 6-8.', 'EPIC-031 plan §5 + D16 Notion page 3a7ca37f935b81ce8e88dff8a505fb12 (worked example); approved by Kerwin 2026-07-24. UNVERIFIED against repo research reports — no repo source names a 3-5 block inside hypertrophy programs; research-citation upgrade flagged, not fabricated.', 'e636007d-194f-4440-a2cc-9bc514957c64')
on conflict (principle_key) do update set
  claim = excluded.claim, rationale = excluded.rationale, source_citation = excluded.source_citation;

-- ── Brick by Brick (brick-by-brick) — from seeds/brick-by-brick.json ──
do $$
declare tid uuid; bid uuid; did uuid; eid uuid;
begin
  insert into public.workout_templates
    (name, slug, author_id, is_published, author_attribution, parent_goal,
     code_goal_mapping, duration_weeks, days_per_week, split_type,
     intensity_tier, difficulty, tagline, description, coaching_notes,
     science_overrides, source_provenance)
  values ('Brick by Brick', 'brick-by-brick', 'e636007d-194f-4440-a2cc-9bc514957c64', true, 'Tandem', 'build_muscle',
     'build_muscle', 12, 4, 'body_part',
     'full_gym', 'intermediate', 'Twelve weeks. Four days. Zero guesswork.', 'A 12-week body-part split built the old way and programmed the new way: the same first lift for every muscle all twelve weeks, three 4-week phases that walk reps from 12-15 down to a heavy 3-5 finish, and every fourth week pulled back on purpose.', 'Primaries never change — that is the point. Log the same lift for twelve weeks and watch the bar load climb. Rest-pause and drop sets appear only on weeks 1-3 of the first two phases; deload and test weeks run clean.',
     '{"rep_floor":3}'::jsonb, '{"inspiration":"classic body-part split era","rebuild":"own-brand, Tandem-authored","authored":"2026-07-24"}'::jsonb)
  on conflict (slug) do update set
    name = excluded.name, author_attribution = excluded.author_attribution,
    parent_goal = excluded.parent_goal, code_goal_mapping = excluded.code_goal_mapping,
    duration_weeks = excluded.duration_weeks, days_per_week = excluded.days_per_week,
    split_type = excluded.split_type, intensity_tier = excluded.intensity_tier,
    difficulty = excluded.difficulty, tagline = excluded.tagline,
    description = excluded.description, coaching_notes = excluded.coaching_notes,
    science_overrides = excluded.science_overrides,
    source_provenance = excluded.source_provenance, updated_at = now()
  returning id into tid;
  delete from public.template_blocks where template_id = tid;

  insert into public.template_blocks (template_id, block_order, week_start, week_end, name, rep_scheme_by_week, technique_by_week)
  values (tid, 1, 1, 4, 'Phase 1 — Base', '{"1":"12-15 primaries","2":"12-15 primaries","3":"12-15 primaries","4":"deload — volume cut"}'::jsonb, '{"1":"rest_pause","2":"rest_pause","3":"rest_pause","4":"none"}'::jsonb)
  returning id into bid;
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 1, 'Chest + Triceps', array['chest','triceps']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'flat-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '12-15', 90, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'incline-db-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '12-15', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'close-grip-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '12-15', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '12-15', 60, 'accessory', 'rest_pause', false);
  select id into strict eid from public.exercises where slug = 'skull-crusher';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '12-15', 60, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'tricep-rope-pushdown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '12-15', 60, 'accessory', 'rest_pause', false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 2, 'Back + Biceps + Abs', array['back','biceps','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '12-15', 90, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'lat-pulldown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '12-15', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'seated-cable-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '12-15', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'barbell-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '12-15', 60, 'accessory', 'rest_pause', false);
  select id into strict eid from public.exercises where slug = 'incline-db-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '12-15', 60, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'cable-crunch';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '12-15', 45, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'hanging-leg-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '12-15', 45, 'core', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 3, 'Shoulders + Traps + Calves', array['shoulders','traps','calves']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-ohp';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '12-15', 90, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'seated-db-shoulder-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '12-15', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'db-lateral-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '12-15', 60, 'accessory', 'rest_pause', false);
  select id into strict eid from public.exercises where slug = 'reverse-pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '12-15', 60, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'shrug-barbell';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '12-15', 60, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'standing-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '12-15', 60, 'accessory', 'rest_pause', false);
  select id into strict eid from public.exercises where slug = 'seated-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '12-15', 60, 'accessory', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 4, 'Legs + Abs', array['quads','hamstrings','glutes','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-back-squat';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '12-15', 90, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'romanian-deadlift';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '12-15', 90, 'secondary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'leg-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '12-15', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'leg-extension';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '12-15', 60, 'accessory', 'rest_pause', false);
  select id into strict eid from public.exercises where slug = 'lying-leg-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '12-15', 60, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'weighted-decline-sit-up';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '12-15', 45, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'ab-wheel-rollout';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '12-15', 45, 'core', null, false);

  insert into public.template_blocks (template_id, block_order, week_start, week_end, name, rep_scheme_by_week, technique_by_week)
  values (tid, 2, 5, 8, 'Phase 2 — Build', '{"1":"9-11 primaries","2":"9-11 primaries","3":"9-11 primaries","4":"deload — volume cut"}'::jsonb, '{"1":"drop_set","2":"drop_set","3":"drop_set","4":"none"}'::jsonb)
  returning id into bid;
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 1, 'Chest + Triceps', array['chest','triceps']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'flat-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '9-11', 120, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'incline-db-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '9-11', 105, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'close-grip-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '9-11', 105, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '9-11', 75, 'accessory', 'drop_set', false);
  select id into strict eid from public.exercises where slug = 'skull-crusher';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '9-11', 75, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'tricep-rope-pushdown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '9-11', 75, 'accessory', 'drop_set', false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 2, 'Back + Biceps + Abs', array['back','biceps','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '9-11', 120, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'lat-pulldown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '9-11', 105, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'seated-cable-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '9-11', 105, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'barbell-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '9-11', 75, 'accessory', 'drop_set', false);
  select id into strict eid from public.exercises where slug = 'incline-db-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '9-11', 75, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'cable-crunch';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 45, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'hanging-leg-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '10-12', 45, 'core', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 3, 'Shoulders + Traps + Calves', array['shoulders','traps','calves']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-ohp';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '9-11', 120, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'seated-db-shoulder-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '9-11', 105, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'db-lateral-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '9-11', 75, 'accessory', 'drop_set', false);
  select id into strict eid from public.exercises where slug = 'reverse-pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '9-11', 75, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'shrug-barbell';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '9-11', 75, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'standing-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '9-11', 75, 'accessory', 'drop_set', false);
  select id into strict eid from public.exercises where slug = 'seated-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '9-11', 75, 'accessory', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 4, 'Legs + Abs', array['quads','hamstrings','glutes','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-back-squat';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '9-11', 120, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'romanian-deadlift';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '9-11', 105, 'secondary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'leg-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '9-11', 105, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'leg-extension';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '9-11', 75, 'accessory', 'drop_set', false);
  select id into strict eid from public.exercises where slug = 'lying-leg-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '9-11', 75, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'weighted-decline-sit-up';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 45, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'ab-wheel-rollout';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '10-12', 45, 'core', null, false);

  insert into public.template_blocks (template_id, block_order, week_start, week_end, name, rep_scheme_by_week, technique_by_week)
  values (tid, 3, 9, 12, 'Phase 3 — Peak', '{"1":"3-5 primaries","2":"3-5 primaries","3":"3-5 primaries","4":"realization — top set"}'::jsonb, '{"1":"none","2":"none","3":"none","4":"none"}'::jsonb)
  returning id into bid;
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 1, 'Chest + Triceps', array['chest','triceps']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'flat-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '3-5', 180, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'incline-db-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '6-8', 120, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'close-grip-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '6-8', 120, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '6-8', 90, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'skull-crusher';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '6-8', 90, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'tricep-rope-pushdown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '6-8', 90, 'accessory', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 2, 'Back + Biceps + Abs', array['back','biceps','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '3-5', 180, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'lat-pulldown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '6-8', 120, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'seated-cable-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '6-8', 120, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'barbell-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '6-8', 90, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'incline-db-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '6-8', 90, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'cable-crunch';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '8-10', 60, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'hanging-leg-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '8-10', 60, 'core', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 3, 'Shoulders + Traps + Calves', array['shoulders','traps','calves']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-ohp';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '3-5', 180, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'seated-db-shoulder-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '6-8', 120, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'db-lateral-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '6-8', 90, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'reverse-pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '6-8', 90, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'shrug-barbell';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '6-8', 90, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'standing-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '6-8', 90, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'seated-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '6-8', 90, 'accessory', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 4, 'Legs + Abs', array['quads','hamstrings','glutes','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-back-squat';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '3-5', 180, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'romanian-deadlift';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '6-8', 120, 'secondary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'leg-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '6-8', 120, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'leg-extension';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '6-8', 90, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'lying-leg-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '6-8', 90, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'weighted-decline-sit-up';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '8-10', 60, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'ab-wheel-rollout';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '8-10', 60, 'core', null, false);

  insert into public.program_principles (principle_key, claim, rationale, source_citation, created_by, template_id)
  values ('rep_floor', 'A final-phase 3-5 rep strength block is legal inside a build_muscle (hypertrophy) program, deviating from the D10 band floor of 6.', 'Phase potentiation: after eight weeks of 12-15 and 9-11 hypertrophy work, a short heavy block converts accumulated volume into expressible strength and feeds the week-12 realization test. Scoped to primary lifts in phase 3 only; accessories stay at 6-8.', 'EPIC-031 plan §5 + D16 Notion page 3a7ca37f935b81ce8e88dff8a505fb12 (worked example); approved by Kerwin 2026-07-24. UNVERIFIED against repo research reports — no repo source names a 3-5 block inside hypertrophy programs; research-citation upgrade flagged, not fabricated.', 'e636007d-194f-4440-a2cc-9bc514957c64', tid)
  on conflict (principle_key) do update set
    claim = excluded.claim, rationale = excluded.rationale,
    source_citation = excluded.source_citation, template_id = excluded.template_id;
end $$;

-- ── Redline Recomp (redline-recomp) — from seeds/redline-recomp.json ──
do $$
declare tid uuid; bid uuid; did uuid; eid uuid;
begin
  insert into public.workout_templates
    (name, slug, author_id, is_published, author_attribution, parent_goal,
     code_goal_mapping, duration_weeks, days_per_week, split_type,
     intensity_tier, difficulty, tagline, description, coaching_notes,
     science_overrides, source_provenance)
  values ('Redline Recomp', 'redline-recomp', 'e636007d-194f-4440-a2cc-9bc514957c64', true, 'Tandem', 'transform',
     'transform', 12, 4, 'body_part',
     'full_gym', 'intermediate', 'Same iron. No sitting down.', 'Brick by Brick’s chassis run at recomp pace: the same fixed primaries and 4-day split, but short rests and cardioacceleration bursts between accessory sets keep the heart rate up while the bar still goes up.', 'Cardioacceleration means 30-60 seconds of jumping jacks, high knees, or bike between accessory sets instead of sitting. Primaries are still trained heavy and rested honestly — never rush the first lift. Deload and test weeks run clean.',
     '{}'::jsonb, '{"inspiration":"Brick by Brick chassis + cardioacceleration variant","rebuild":"own-brand, Tandem-authored","authored":"2026-07-24"}'::jsonb)
  on conflict (slug) do update set
    name = excluded.name, author_attribution = excluded.author_attribution,
    parent_goal = excluded.parent_goal, code_goal_mapping = excluded.code_goal_mapping,
    duration_weeks = excluded.duration_weeks, days_per_week = excluded.days_per_week,
    split_type = excluded.split_type, intensity_tier = excluded.intensity_tier,
    difficulty = excluded.difficulty, tagline = excluded.tagline,
    description = excluded.description, coaching_notes = excluded.coaching_notes,
    science_overrides = excluded.science_overrides,
    source_provenance = excluded.source_provenance, updated_at = now()
  returning id into tid;
  delete from public.template_blocks where template_id = tid;

  insert into public.template_blocks (template_id, block_order, week_start, week_end, name, rep_scheme_by_week, technique_by_week)
  values (tid, 1, 1, 4, 'Phase 1 — Base', '{"1":"10-12 primaries","2":"10-12 primaries","3":"10-12 primaries","4":"deload — volume cut"}'::jsonb, '{"1":"cardioacceleration","2":"cardioacceleration","3":"cardioacceleration","4":"none"}'::jsonb)
  returning id into bid;
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 1, 'Chest + Triceps', array['chest','triceps']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'flat-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '10-12', 90, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'incline-db-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '10-12', 60, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'close-grip-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '10-12', 60, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'skull-crusher';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '10-12', 40, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'tricep-rope-pushdown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 2, 'Back + Biceps + Abs', array['back','biceps','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '10-12', 90, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'lat-pulldown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '10-12', 60, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'seated-cable-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '10-12', 60, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'barbell-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'incline-db-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '10-12', 40, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'cable-crunch';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 30, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'hanging-leg-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '10-12', 30, 'core', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 3, 'Shoulders + Traps + Calves', array['shoulders','traps','calves']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-ohp';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '10-12', 90, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'seated-db-shoulder-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '10-12', 60, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'db-lateral-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'reverse-pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '10-12', 40, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'shrug-barbell';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '10-12', 40, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'standing-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'seated-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '10-12', 40, 'accessory', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 4, 'Legs + Abs', array['quads','hamstrings','glutes','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-back-squat';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '10-12', 90, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'romanian-deadlift';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '10-12', 60, 'secondary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'leg-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '10-12', 60, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'leg-extension';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'lying-leg-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '10-12', 40, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'weighted-decline-sit-up';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 30, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'ab-wheel-rollout';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '10-12', 30, 'core', null, false);

  insert into public.template_blocks (template_id, block_order, week_start, week_end, name, rep_scheme_by_week, technique_by_week)
  values (tid, 2, 5, 8, 'Phase 2 — Build', '{"1":"8-10 primaries","2":"8-10 primaries","3":"8-10 primaries","4":"deload — volume cut"}'::jsonb, '{"1":"cardioacceleration","2":"cardioacceleration","3":"cardioacceleration","4":"none"}'::jsonb)
  returning id into bid;
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 1, 'Chest + Triceps', array['chest','triceps']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'flat-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '8-10', 105, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'incline-db-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '8-10', 75, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'close-grip-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '8-10', 75, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'skull-crusher';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '10-12', 40, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'tricep-rope-pushdown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 2, 'Back + Biceps + Abs', array['back','biceps','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '8-10', 105, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'lat-pulldown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '8-10', 75, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'seated-cable-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '8-10', 75, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'barbell-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'incline-db-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '10-12', 40, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'cable-crunch';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 30, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'hanging-leg-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '10-12', 30, 'core', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 3, 'Shoulders + Traps + Calves', array['shoulders','traps','calves']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-ohp';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '8-10', 105, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'seated-db-shoulder-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '8-10', 75, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'db-lateral-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'reverse-pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '10-12', 40, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'shrug-barbell';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '10-12', 40, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'standing-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'seated-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '10-12', 40, 'accessory', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 4, 'Legs + Abs', array['quads','hamstrings','glutes','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-back-squat';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '8-10', 105, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'romanian-deadlift';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '8-10', 75, 'secondary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'leg-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '8-10', 75, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'leg-extension';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '10-12', 40, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'lying-leg-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '10-12', 40, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'weighted-decline-sit-up';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 30, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'ab-wheel-rollout';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '10-12', 30, 'core', null, false);

  insert into public.template_blocks (template_id, block_order, week_start, week_end, name, rep_scheme_by_week, technique_by_week)
  values (tid, 3, 9, 12, 'Phase 3 — Peak', '{"1":"8-10 primaries","2":"8-10 primaries","3":"8-10 primaries","4":"realization — top set"}'::jsonb, '{"1":"cardioacceleration","2":"cardioacceleration","3":"cardioacceleration","4":"none"}'::jsonb)
  returning id into bid;
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 1, 'Chest + Triceps', array['chest','triceps']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'flat-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '8-10', 120, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'incline-db-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '8-10', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'close-grip-barbell-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '8-10', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '8-10', 45, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'skull-crusher';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '8-10', 45, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'tricep-rope-pushdown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '8-10', 45, 'accessory', 'cardioacceleration', false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 2, 'Back + Biceps + Abs', array['back','biceps','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '8-10', 120, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'lat-pulldown';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '8-10', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'seated-cable-row';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '8-10', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'barbell-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '8-10', 45, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'incline-db-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '8-10', 45, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'cable-crunch';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 30, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'hanging-leg-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '10-12', 30, 'core', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 3, 'Shoulders + Traps + Calves', array['shoulders','traps','calves']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-ohp';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '8-10', 120, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'seated-db-shoulder-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '8-10', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'db-lateral-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '8-10', 45, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'reverse-pec-deck';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '8-10', 45, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'shrug-barbell';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '8-10', 45, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'standing-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '8-10', 45, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'seated-calf-raise';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '8-10', 45, 'accessory', null, false);
  insert into public.template_days (template_id, block_id, day_order, label, muscle_targets)
  values (tid, bid, 4, 'Legs + Abs', array['quads','hamstrings','glutes','abs']::text[]) returning id into did;
  select id into strict eid from public.exercises where slug = 'barbell-back-squat';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 1, 4, '8-10', 120, 'primary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'romanian-deadlift';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 2, 3, '8-10', 90, 'secondary_compound', null, true);
  select id into strict eid from public.exercises where slug = 'leg-press';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 3, 3, '8-10', 90, 'secondary_compound', null, false);
  select id into strict eid from public.exercises where slug = 'leg-extension';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 4, 3, '8-10', 45, 'accessory', 'cardioacceleration', false);
  select id into strict eid from public.exercises where slug = 'lying-leg-curl';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 5, 3, '8-10', 45, 'accessory', null, false);
  select id into strict eid from public.exercises where slug = 'weighted-decline-sit-up';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 6, 3, '10-12', 30, 'core', null, false);
  select id into strict eid from public.exercises where slug = 'ab-wheel-rollout';
  insert into public.template_exercises (day_id, exercise_id, ex_order, sets, reps, rest, role, technique, constant_across_program)
  values (did, eid, 7, 3, '10-12', 30, 'core', null, false);
end $$;
