// EXERCISE_BANK → exercises seed SQL emitter — THE one home for this rule.
//
// Both the generator (scripts/sync-exercise-bank.mjs, which writes the file)
// and the freshness gate (scripts/bank-seed-freshness.mjs, which asserts the
// committed file still matches the bank) import from here. A second copy of
// this emitter would drift from the first, and a gate asserting a stale copy
// is worse than no gate — it manufactures confidence. One rule, one home.
//
// EPIC-026 tags (movement_pattern/unilateral/complexity/position_bias) are
// intentionally NOT emitted — no source names them yet; they stay NULL
// (DOCTRINE: flag a gap, never fabricate).
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
export const SEED_PATH = path.join(root, 'migrations', 'epic031_exercises_seed.sql');

const q = (s) => s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`;
const arr = (a) => `array[${(a || []).map(q).join(',')}]::text[]`;
const num = (n) => (n == null || !Number.isFinite(Number(n))) ? 'null' : String(n);

const ALLOWED_EQ = new Set(['barbell','dumbbell','cable','machine','bodyweight','band']);
const ALLOWED_TIER = new Set(['home','hotel_gym','full_gym']);
const ALLOWED_CAT = new Set(['compound','isolation','core','cardio']);
const ALLOWED_UNIT = new Set(['reps','sec','bw']);

// Extract EXERCISE_BANK LIVE from programs.js (source-first: never a copied
// list) and emit one VALUES row per slug.
export function buildRows() {
  const src = fs.readFileSync(path.join(root, 'programs.js'), 'utf8');

  const ctx = { window: {}, document: { querySelectorAll: () => [] },
                localStorage: { getItem: () => null, setItem: () => {} } };
  vm.createContext(ctx);
  vm.runInContext(src + ';globalThis.__BANK = EXERCISE_BANK;', ctx);
  const bank = ctx.__BANK;
  const slugs = Object.keys(bank);
  if (slugs.length < 100) throw new Error(`Bank suspiciously small (${slugs.length}) — extraction broken?`);

  // public.exercises carries UNIQUE(name) as well as UNIQUE(slug), but the
  // emitted statement can only arbitrate `on conflict (slug)`. A bank edit
  // that duplicates a name therefore fails at APPLY time on exercises_name_key
  // — unhandled, mid-statement, against prod. Catch it here instead.
  const seenNames = new Map();

  const rows = [];
  for (const slug of slugs) {
    const e = bank[slug];
    // Validate against the table's CHECK constraints BEFORE emitting — fail loud
    // here rather than at apply time.
    if (!ALLOWED_TIER.has(e.tier)) throw new Error(`${slug}: bad tier ${e.tier}`);
    if (!ALLOWED_CAT.has(e.category)) throw new Error(`${slug}: bad category ${e.category}`);
    if (e.equipment != null && !ALLOWED_EQ.has(e.equipment)) throw new Error(`${slug}: bad equipment ${e.equipment}`);
    const unit = e.unit || 'reps';
    if (!ALLOWED_UNIT.has(unit)) throw new Error(`${slug}: bad unit ${unit}`);
    if (seenNames.has(e.name)) {
      throw new Error(`duplicate exercise name ${JSON.stringify(e.name)} on slugs ` +
        `'${seenNames.get(e.name)}' and '${slug}' — violates exercises_name_key, ` +
        `which 'on conflict (slug)' cannot absorb. Rename one before regenerating.`);
    }
    seenNames.set(e.name, slug);

    rows.push(`(${q(slug)}, ${q(e.name)}, ${q(e.tier)}, ${q(e.category)}, ` +
      `${arr(e.muscleGroups?.primary)}, ${arr(e.muscleGroups?.secondary)}, ${arr(e.emphasis)}, ` +
      `${num(e.oneRmFactor)}, ${q(unit)}, ${num(e.secs)}, ${q(e.videoId)}, ` +
      `${q(e.why)}, ${arr(e.cues)}, ${q(e.equipment)})`);
  }
  return rows;
}

// The `-- Generated:` line is the ONLY part of the file that legitimately
// changes without the bank changing, so it is the only line the freshness
// comparison is allowed to ignore.
export const GENERATED_LINE = /^-- Generated: .*$/m;
export const normalise = (sql) => sql.replace(GENERATED_LINE, '-- Generated: <ignored>');

export function buildSeedSql(generatedAt = new Date().toISOString()) {
  const rows = buildRows();
  return `-- ============================================================================
-- EPIC-031 — exercises seed (GENERATED FILE — do not hand-edit)
-- Generated by scripts/sync-exercise-bank.mjs from programs.js EXERCISE_BANK
-- Generated: ${generatedAt} · entries: ${rows.length}
-- Idempotent: upsert on slug. EPIC-026 tag columns left NULL by design.
-- DO NOT apply to live Supabase before Kerwin's SQL review.
-- ============================================================================
insert into public.exercises
  (slug, name, tier, category, muscle_primary, muscle_secondary, emphasis,
   one_rm_factor, unit, secs, video_id, why, cues, equipment)
values
${rows.join(',\n')}
on conflict (slug) do update set
  name = excluded.name,
  tier = excluded.tier,
  category = excluded.category,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  emphasis = excluded.emphasis,
  one_rm_factor = excluded.one_rm_factor,
  unit = excluded.unit,
  secs = excluded.secs,
  video_id = excluded.video_id,
  why = excluded.why,
  cues = excluded.cues,
  equipment = excluded.equipment;
`;
}
