#!/usr/bin/env python3
"""
build-musclemap-asset.py — packs the traced regions (trace-musclemap.py) and
their muscle labels (label-musclemap.py) into public/musclemap-paths.js, the
runtime asset tandem.html loads for the Wave 4 muscle heatmap.

Shape:
  window.MUSCLEMAP = {
    male:   { w, h, regions: [[key|null, "M..Z"], ...] },
    female: { ... }
  }
key is a heatmap display bucket (see label-musclemap.py PALETTE); null = body
silhouette region (head/hands/feet/neck) rendered in the neutral fill so the
figure stays whole.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "scripts", "musclemap")

payload = {}
for sex in ("male", "female"):
    with open(os.path.join(OUT, f"{sex}-regions.json")) as f:
        data = json.load(f)
    with open(os.path.join(OUT, f"{sex}-labels.json")) as f:
        labels = json.load(f)
    regions = []
    for r in data["regions"]:
        key = labels[str(r["id"])]
        regions.append([None if key == "drop" else key, r["d"]])
    payload[sex] = {"w": data["width"], "h": data["height"], "regions": regions}

js = "// GENERATED by scripts/build-musclemap-asset.py — do not hand-edit.\n" \
     "// Source art: public/musclemap-{male,female}.webp; labels: scripts/musclemap/*-labels.json.\n" \
     "window.MUSCLEMAP = " + json.dumps(payload, separators=(",", ":")) + ";\n"
dest = os.path.join(ROOT, "public", "musclemap-paths.js")
with open(dest, "w") as f:
    f.write(js)
print(f"wrote {dest} ({os.path.getsize(dest) // 1024} KB)")
